title: Evan Carr
description: Information Science senior at UMD with a dual focus in Data Analytics and Cybersecurity, bringing hands-on experience in SQL, machine learning, and security tools including Splunk, Microsoft Azure, and Zscaler. Seeking opportunities in SOC analysis, data analytics, or IT security.
linkedin: https://www.linkedin.com/in/evan-carr-
show_downloads: True
theme: jekyll-theme-minimal
